### ISSUE TITLE
Wrong dataset?

### ISSUE THREAD

**Issue by ehhhhjw** [prastunlp/DualDec#2]
Hi, when running this code an error is reported:
Traceback (most recent call last):
  File "train.py", line 102, in <module>
    train_batch = DataLoader(tokenizer, train_data, predicate2id, subj_type2id, obj_type2id, opt['batch_size'])
  File "/webdav/MyData/hjw_project/text_instruction/experience_code/DualDec-master/utils/loader.py", line 88, in __init__
    data = self.preprocess_bert(data,tokenizer)
  File "/webdav/MyData/hjw_project/text_instruction/experience_code/DualDec-master/utils/loader.py", line 168, in preprocess_bert
    text = d['tokens']
KeyError: 'tokens'
I traced this error and found that 'token' does not exist in the train.json file with 'spo_list','spo_details' attributes.

**Comment by 258508** [comment]
请问这个问题你解决了吗？
